### ISSUE TITLE
floatをバイト列に変換する過程で、floatを整数に変換しているためオーバーフローが起きている

### ISSUE THREAD

**Issue by shosatojp** [MIKUEC2020/PositionStreamServer#1]
7fb2a87530b90bd27623e0a203a12bfc0751654b でバグが入っていたので報告します

# 問題

User#RadYはfloatだがintに変換している

https://github.com/MIKUEC2020/PositionStreamServer/blob/5e6bdb4788fb4bfffeda6d668ee72c6a7997e8b5/StreamServerCommonLibrary/Utility.cs#L91

一旦floatに型変換されるが、再びintに変換されている

https://github.com/MIKUEC2020/PositionStreamServer/blob/5e6bdb4788fb4bfffeda6d668ee72c6a7997e8b5/StreamServerCommonLibrary/PacketUtil.cs#L50-L59

valueにbyte型の範囲外の数が入るとオーバーフローを起こす

```
System.OverflowException: Value was either too large or too small for an unsigned byte.
   at System.Convert.ThrowByteOverflowException()
   at System.Convert.ToByte(String value, Int32 fromBase)
   at CommonLibrary.PacketUtil.ConvertByte(Single value) in /home/sho/repos/PositionStreamServer/StreamServerCommonLibrary/PacketUtil.cs:line 57
   at CommonLibrary.Utility.PacketToBuffer(MinimumAvatarPacket packet) in /home/sho/repos/PositionStreamServer/StreamServerCommonLibrary/Utility.cs:line 91
   at StreamClient.OutputLoop.Update(Int32 count) in /home/sho/repos/PositionStreamServer/StreamClient/Source/StreamClient/OutputLoop.cs:line 38
   at LoopLibrary.BaseLoop`1.Loop(CancellationToken token) in /home/sho/repos/PositionStreamServer/LoopLibrary/BaseLoop.cs:line 37
```

**Comment by Taku3939** [comment]
了解です修正しておきます

**Comment by Taku3939** [comment]
# Bug Fix

- 指定のバグ修正の箇所とConvertByteでAnd演算していた箇所がエラーを起こしていたので修正を行いました.

  https://github.com/MIKUEC2020/PositionStreamServer/blob/c5b6ec96efe5433085c18c1a0704d082f1006e05/StreamServerCommonLibrary/PacketUtil.cs#L47-L60

- パケットの範囲外エラーはインスタンス生成後にCheckRange関数でパケットの長さをnullチェックを行うこaとによって対処を行いました

  https://github.com/MIKUEC2020/PositionStreamServer/blob/c5b6ec96efe5433085c18c1a0704d082f1006e05/StreamServerCommonLibrary/MinimumAvatarPacket.cs#L51-L59
